language: python

env:
  global:
    - COVERALLS_SERVICE_NAME=travis-pro

python:
  - "3.11"

services:
  - docker

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r treestagram_project/requirements.txt

script:
  - cd treestagram_project
  - black --check .
  - flake8 .
  - python manage.py migrate
  - coverage run --source=accounts,caretaker,chat,posts,trees,treestagram manage.py test
  # - coverage run --source=accounts,trees,treestagram,caretaker,posts manage.py test # This is the old one

after_success:
  - coveralls

# deploy:
#   - provider: elasticbeanstalk
#     region: us-east-1
#     app: treestagram_project
#     env: treestagram-main
#     bucket_name: elasticbeanstalk-us-east-1-288378107443
#     access_key_id: $AWS_ACCESS_KEY_ID
#     secret_access_key: $AWS_SECRET_ACCESS_KEY
#     on:
#       branch: main

#   - provider: elasticbeanstalk
#     region: us-east-1
#     app: treestagram_project
#     env: treestagram-dev
#     bucket_name: elasticbeanstalk-us-east-1-288378107443
#     access_key_id: $AWS_ACCESS_KEY_ID
#     secret_access_key: $AWS_SECRET_ACCESS_KEY
#     on:
#       branch: develop

# # Ramsey's -----------------------------------------
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: treestagram11
#   env: treestagram-env11
#   bucket_name: elasticbeanstalk-us-east-1-180382394287-1
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   on:
#     branch: develop 
# # Ramsey's -----------------------------------------


# # Sumit's -----------------------------------------
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: treestagram
  env: treestagram-env
  bucket_name: elasticbeanstalk-us-east-1-563336977573
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    branch: develop 

deploy:
  - provider: elasticbeanstalk
    region: us-east-1
    app: treestagram
    env: Treestagram-main-env
    bucket_name: elasticbeanstalk-us-east-1-563336977573
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    on:
      branch: main

# Faiz's ------------------------------------------

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: treestagramf5
#   env: treestagram-envf5
#   bucket_name: elasticbeanstalk-us-east-1-321495243079
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   on:
#     branch: develop 

# Adhyayan's ------------------------------------------

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: treestagrama1
#   env: treestagram-enva1
#   bucket_name: elasticbeanstalk-us-east-1-227176596642
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   on:
#     branch: develop 
