# Generated by Django 5.2.12 on 2026-04-21 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tree_id", models.CharField(max_length=50)),
                ("curb_loc", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("health", models.CharField(blank=True, max_length=50)),
                ("sidewalk", models.CharField(blank=True, max_length=50)),
                ("root_stone", models.CharField(blank=True, max_length=10)),
                ("root_grate", models.CharField(blank=True, max_length=10)),
                ("root_other", models.CharField(blank=True, max_length=10)),
                ("trunk_wire", models.CharField(blank=True, max_length=10)),
                ("trnk_light", models.CharField(blank=True, max_length=10)),
                ("trnk_other", models.CharField(blank=True, max_length=10)),
                ("brch_light", models.CharField(blank=True, max_length=10)),
                ("brch_shoe", models.CharField(blank=True, max_length=10)),
                ("brch_other", models.CharField(blank=True, max_length=10)),
                ("tree_dbh", models.CharField(blank=True, max_length=20)),
                ("stump_diam", models.CharField(blank=True, max_length=20)),
                ("problems", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status_field",
                    models.CharField(
                        choices=[("pending", "Pending"), ("dismissed", "Dismissed")],
                        db_column="request_status",
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
