# Generated by Django 6.0.3 on 2026-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.IntegerField(unique=True)),
                ('created_at', models.CharField(max_length=50)),
                ('tree_dbh', models.IntegerField()),
                ('stump_diam', models.IntegerField()),
                ('curb_loc', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('health', models.CharField(max_length=20)),
                ('spc_latin', models.CharField(max_length=100)),
                ('spc_common', models.CharField(max_length=100)),
                ('sidewalk', models.CharField(max_length=20)),
                ('problems', models.CharField(blank=True, max_length=200, null=True)),
                ('root_stone', models.BooleanField()),
                ('root_grate', models.BooleanField()),
                ('root_other', models.BooleanField()),
                ('trunk_wire', models.BooleanField()),
                ('trnk_light', models.BooleanField()),
                ('trnk_other', models.BooleanField()),
                ('brch_light', models.BooleanField()),
                ('brch_shoe', models.BooleanField()),
                ('brch_other', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('zip_city', models.CharField(max_length=50)),
                ('borough', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
