# Generated by Django 6.0.3 on 2026-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tree",
            name="latitude",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="tree",
            name="longitude",
            field=models.FloatField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="tree",
            index=models.Index(
                fields=["latitude", "longitude"], name="trees_tree_latitud_b623f8_idx"
            ),
        ),
    ]
