# Generated by Django 6.0.3 on 2026-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="comment",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="post",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tagged_users",
        ),
        migrations.AddField(
            model_name="user",
            name="followed_trees_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
