# Generated by Django 6.0.3 on 2026-03-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_image_alter_treephoto_photos"),
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="trees.tree",
            ),
        ),
    ]
