# Generated by Django 6.0.3 on 2026-03-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_treefollow"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
