# Generated by Django 6.0.3 on 2026-03-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_delete_chatmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TreePhoto",
        ),
    ]
